[project]
name = "organic-food-tracebality"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "lightgbm>=4.7.0",
    "mysql-connector-python>=26.7.0",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "pymysql>=1.2.0",
    "scikit-learn>=1.9.0",
    "streamlit>=1.60.0",
    "xgboost>=3.4.1",
]
